### PR TITLE
Fixed topbar table names

### LINKED ISSUE #17: Let's not show name in all uppercase
https://www.loom.com/share/220bc7c240ea4ffdb1c3f34be482a207

See the homepage of ActiveAdmin to see how they display the names at the top 

@Anamika-123 _a

### PR DESCRIPTION
**Pull request by Anamika-123**
Fix #17

### CODE REVIEW

File: app/javascript/src/components/NeetoArea51/index.jsx [hunk 1]
```diff
@@ -72,14 +72,14 @@ const NeetoArea51 = () => {
           {names.map((name, index) => (
             < Tab.Item
```
Comment (chiraggshah) [inline app/javascript/src/components/NeetoArea51/index.jsx:73]: Remove the extra space between `<` and `T`

**Review by chiraggshah — APPROVED** [review]
@Anamika-123 _a : Looks good. One comment unrelated to the changes made. You can fix that and get it merged.

File: app/javascript/src/components/NeetoArea51/index.jsx (hunk 1 above)
Comment (Anamika-123) [reply app/javascript/src/components/NeetoArea51/index.jsx]: Done.
